### ISSUE TITLE
Add new additional_http_headers configuration

### ISSUE THREAD

**Issue by xuantuan58** [treasure-data/embulk-output-td#93]
Allow user to add extra headers to requests will send to TD.

The new configuration will be in a form of:
```yaml
out:
  type: td
  apikey: ...
  ...
  additional_http_headers:
    name: value
    other_name: other_value
  ...
```
